### ISSUE TITLE
Unknown checkbox

### ISSUE THREAD

**Issue by designfusionjb** [HanSolo/JDKMon#29] opened 2021-10-05 12:44 UTC
In the Windows 10 version of 17.0.6 there is a checkbox that is missing a label.

![image](https://user-images.githubusercontent.com/29737883/136024681-aad9a8ef-3142-4e48-aa11-9e02f225d0f0.png)

![image](https://user-images.githubusercontent.com/29737883/136024849-fc3c99a2-f06e-4552-a301-334df32f09bd.png)

**Comment by HanSolo** [comment] 2021-10-05 12:54
Duplicate of issue #18

**Closed by HanSolo** 2021-10-05 12:54 UTC
Labels: duplicate
